### ISSUE TITLE
We need a PFP/Logo

### ISSUE THREAD

**Issue by ninjamar** [scratch-advancedtopics/.github#1]
We need a PFP/Logo for the organization

**Comment by Wafelix** [comment]
<img width="277" alt="E95B5A85-D2FA-433F-B1D6-139B06DD32EF-removebg-preview" src="https://user-images.githubusercontent.com/65729023/137836152-78de1899-6e63-47b2-b757-20d59871d40b.png">
This took me almost an entire 10 minutes :)

**Comment by Wafelix** [comment]
@WaffelEntertainment

**Comment by ninjamar** [comment]
> ![ATs GH LOGO](https://user-images.githubusercontent.com/67440879/139429772-c85954fd-bccb-4e2a-a341-7470210c1a94.png)
> 
> here ^
> 
> also @ninjamar please add me to the org

gud logo also i invited u

**Comment by ninjamar** [comment]
could you send me the url of the image? github make the image look weird

**Comment by FunctionalMetatable** [comment]
PNG: https://assets.scratch.mit.edu/get_image/.%2E/154b04a101f6175dc4817113002d2b37.png
SVG: https://assets.scratch.mit.edu/get_image/.%2E/82a923b21028fb436ba3a8f12e5e42ba.svg

**Comment by ninjamar** [comment]
> PNG: https://assets.scratch.mit.edu/get_image/.%2E/154b04a101f6175dc4817113002d2b37.png SVG: https://assets.scratch.mit.edu/get_image/.%2E/82a923b21028fb436ba3a8f12e5e42ba.svg

could you move the comment thing closer to the AT sign? github wants me to crop the image. also svg is better

**Comment by FunctionalMetatable** [comment]
https://user-images.githubusercontent.com/67440879/139527138-b0001781-1487-486b-83e6-d14bfe82c17b.png

**Comment by ninjamar** [comment]
done
