### ISSUE TITLE
May I be promoted to an owner of this org?

### ISSUE THREAD

**Issue by MystPi** [scratch-advancedtopics/.github#5]
It would make things a lot easier, @ninjamar. I won't do anything drastic; I'll just invite people if they ask and are a part of the studio, change a few settings on a repo, etc.

Also the GitHub docs say an org should have at least two owners.

https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization

**Comment by ninjamar** [comment]
you could see the email address then

**Comment by MystPi** [comment]
> you could see the email address then

Your email address?

**Comment by ninjamar** [comment]
> > you could see the email address then
> 
> Your email address?

in the settings of the org

**Comment by MystPi** [comment]
> > > you could see the email address then
> > 
> > 
> > Your email address?
> 
> in the settings of the org

Ah, ok then. I'll close this issue; sorry for your time!
