### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by JoshAtticus** [scratch-advancedtopics/.github#7]
Can i be in? I am in studio

I will post "verify:joshatticus" in studio as myself

**Comment by imdevarsh** [comment]
I am in studio too
verify:god286

**Comment by Dhuls-Scratch** [comment]
let's see if i have the permissions to do this
edit: for some reason no. @ninjamar please invite these people or give regular org members permission to invite.

**Comment by imdevarsh** [comment]
hmm

**Comment by ninjamar** [comment]
done

**Comment by Dhuls-Scratch** [comment]
Josh Atticus wasn't invited (the ST deleted their comment). They later said it was them [here](https://scratch.mit.edu/users/JoshAtticus/#comments-177113116).

**Comment by imdevarsh** [comment]
Hmm, I wonder why it was deleted.

**Comment by ninjamar** [comment]
i added @JoshAtticus
